on: push

name: CI

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Version Info
        run: |
          node --version
          npm --version

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
