on: push

name: CI

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 13]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.0.0

      - name: Install Node
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: NPM Install
        run: npm ci

      - name: NPM Build
        run: npm run build

      - name: NPM Test
        run: npm test

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
