name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.1

      - name: Install Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node }}

      - run: yarn install

      - run: yarn test

      - run: yarn build

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v3.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
