on:
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 13]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - run: yarn install

      - run: yarn test

      - run: yarn build

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v1.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
